ico.dir=dir

ico.txt=txt
ico.log=txt

ico.css=css
ico.js=js
ico.as=as
ico.json=json
ico.xml=xml
ico.sql=sql
ico.gra=gra
ico.htm=rtf
ico.html=html
ico.md=md
ico.java=java
ico.jsp=code
ico.py=py
ico.sh=sh

ico.properties=properties
ico.ini=ini
ico.conf=ini
ico.yaml=ini

ico.exe=exe
ico.dll=dll
ico.lib=lib
ico.pt=pt
ico.onnx=onnx
ico.db=db

ico.jpg=img
ico.jpeg=img
ico.png=img2
ico.gif=img2
ico.webp=img2

ico.mp3=mp3
ico.wav=wav
ico.mp4=mp4
ico.avi=avi

ico.chm=chm
ico.pdf=pdf
ico.doc=doc
ico.xls=xls
ico.xlsx=xls
ico.csv=xls

ico.glb=3d

ico.zip=zip
ico.rar=zip
ico.7z=zip
ico.tar=zip

view.mp3=audio/mpeg
view.wav=audio/mpeg
view.mp4=video/mp4
view.pdf=application/pdf

view.js=script
view.sql=sql
view.jv=json

view.jpg=img
view.jpeg=img
view.png=img
view.gif=img
view.bmp=img
view.webp=img

view.txt=text
view.log=text
view.csv=text

view.ini=code
view.conf=code
view.properties=code
view.yaml=code
view.java=code
view.jsp=code
view.py=code
view.sh=code

view.json=code
view.xml=code
view.css=code

view.as=as

view.htm=htm
view.md=markdown
view.gra=graph
view.glb=3d

