log4j.rootLogger=info,Console,Rolling

log4j.appender.Console=org.apache.log4j.ConsoleAppender
log4j.appender.Console.layout=org.apache.log4j.PatternLayout
log4j.appender.Console.layout.ConversionPattern=[%-5p] %d{MM/dd HH:mm:ss.SSS} %l - %m%n
#log4j.appender.Console.Encoding=UTF-8

#DailyRollingFileAppender ??????????,???????????????
log4j.appender.Rolling=org.apache.log4j.RollingFileAppender
log4j.appender.Rolling.layout=org.apache.log4j.PatternLayout
log4j.appender.Rolling.layout.ConversionPattern=%d{MM/dd HH:mm:ss.SSS} - %m%n
log4j.appender.Rolling.MaxFileSize=100MB
log4j.appender.Rolling.MaxBackupIndex=10
log4j.appender.Rolling.File=${catalina.home}/logs/aiot.log

log4j.logger.infc.BaseDevice=info,device,Rolling
log4j.additivity.infc.BaseDevice=false
log4j.appender.device=org.apache.log4j.ConsoleAppender
log4j.appender.device.layout=org.apache.log4j.PatternLayout
log4j.appender.device.layout.ConversionPattern=%d{MM/dd HH:mm:ss.SSS} %m%n